INSERT INTO product (artist_id, title, info, price, kind, img) VALUES
('YOASOBI', '', '', 1300, 'j-pop', 'XSCL-77.jpg'),
('YOASOBI', 'THE BOOK 3 (完全生産限定盤, CD+特製バインダー)', 'HMV限定特典：特製內頁1張(HMV Ver.)', 1960, 'j-pop', 'MO-H-XSCL-75.jpg'),
('YOASOBI', 'THE BOOK 3 (完全生産限定盤, CD+特製バインダー)', '楽天ブックス限定特典：特製內頁1張(楽天ブックス Ver.)+專屬配送箱', 2100, 'j-pop', 'MO-RTB-XSCL-75.jpg'),
('YOASOBI', 'THE BOOK 3 (完全生産限定盤, CD+特製バインダー)', 'SONY官網限定特典：特製內頁1張(SONY官網 ver.)', 1960, 'j-pop', 'MO-SMS-XSCL-75.jpg'),
('YOASOBI', 'THE BOOK 3 (完全生産限定盤, CD+特製バインダー)', 'TOWER限定特典：特製內頁1張(TOWER ver.)', 1860, 'j-pop', 'MO-TR-XSCL-75.jpg'),
('YOASOBI', 'THE BOOK 3 (完全生産限定盤, CD+特製バインダー)', 'TSUTAYA限定特典：特製內頁1張(TSUTAYA ver.)', 1960, 'j-pop', 'MO-TSU-XSCL-75.jpg'),
('YOASOBI', 'THE BOOK 3 (完全生産限定盤, CD+特製バインダー)', '', 1430, 'j-pop', 'XSCL-75.jpg'),
('YOASOBI', 'はじめての - EP (完全生産限定コンプリート盤, CD+Blu-ray+小説4作)', '', 3080, 'j-pop', 'XSCL-70.jpg'),
('YOASOBI', 'はじめての - EP (完全生産限定(色違いのトランプ(「セブンティーン」原作)盤, 8cmCD+小説1作)', '', 740, 'j-pop', 'XSDL-1.jpg'),
('YOASOBI', 'はじめての - EP (完全生産限定(ユーレイ(「海のまにまに」原作)盤, 8cmCD+小説1作)', '', 740, 'j-pop', 'XSDL-3.jpg'),
('YOASOBI', 'はじめての - EP (完全生産限定(ヒカリノタネ(「好きだ」原作)盤, 8cmCD+小説1作)', '', 740, 'j-pop', 'XSDL-5.jpg'),
('YOASOBI', 'はじめての - EP (完全生産限定(私だけの所有者(「ミスター」原作), 8cmCD+小説1作)', '', 740, 'j-pop', 'XSDL-7.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(白))', '7net特典：胸章(數位封面圖像)', 2430, 'j-pop', 'MO-7NET-XSCL-80.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(白))', 'Animate特典：貼紙(數位封面圖像)', 2230, 'j-pop', 'MO-A-XSCL-80.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(黑))', 'Animate特典：貼紙(數位封面圖像)', 2230, 'j-pop', 'MO-A-XSCL-82.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(白))', 'amazon特典：特大封面卡(數位封面圖像)', 2430, 'j-pop', 'MO-AMA-XSCL-80.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(黑))', 'amazon特典：特大封面卡(數位封面圖像)', 2430, 'j-pop', 'MO-AMA-XSCL-82.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(白))', '樂天Books特典：壓克力鑰匙圈(數位封面圖像)', 2230, 'j-pop', 'MO-RTB-XSCL-80.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(黑))', '樂天Books特典：壓克力鑰匙圈(數位封面圖像)', 2230, 'j-pop', 'MO-RTB-XSCL-82.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(白))', 'Sony官網特典：資料夾(A5, YOASOBI Logo圖像)', 2230, 'j-pop', 'MO-SMS-XSCL-80.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(黑))', 'Sony官網特典：資料夾(A5, YOASOBI Logo圖像)', 2230, 'j-pop', 'MO-SMS-XSCL-82.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(白))', '應援店特典：貼紙(YOASOBI Logo圖像)', 2230, 'j-pop', 'MO-TR-XSCL-80.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(黑))', '應援店特典：貼紙(YOASOBI Logo圖像)', 2230, 'j-pop', 'MO-TR-XSCL-82.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(白))', '', 1680, 'j-pop', 'XSCL-80.jpg'),
('YOASOBI', 'Biri-Biri (完全生産限定盤, CD+T-Shirt(黑))', '', 1680, 'j-pop', 'XSCL-82.jpg'),
('YOASOBI', '勇者 (完全生産限定盤, CD+小説+宝箱仕様包裝)', '7net特典：胸章(約75 x 50mm)', 1950, 'j-pop', 'MO-7NET-XSCL-77.jpg'),
('YOASOBI', '勇者 (完全生産盤, CD+小説+宝箱仕様包裝)', 'Animate特典：資料夾(A4)', 1850, 'j-pop', 'MO-A-XSCL-77.jpg'),
('YOASOBI', '勇者 (完全生産限定盤, CD+小説+宝箱仕様包裝)', 'amazon特典：特大封面卡', 1950, 'j-pop', 'MO-AMA-XSCL-77.jpg'),
('YOASOBI', '勇者 (完全生産限定盤, CD+小説+宝箱仕様包裝)', '樂天Books特典：壓克力鑰匙圈(約45 x 65mm)', 1750, 'j-pop', 'MO-RTB-XSCL-77.jpg'),
('YOASOBI', '(索尼進口日版) THE BOOK 2 (完全生產限定盤)', '', 1150, 'j-pop', 'TW-XSCL56.jpg');
